version: "3.9"

services:
  atom:
    build: .
    container_name: atom
    ports:
      - "3000:3000"

    volumes:
      - atom_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

    restart: always
    environment:
      NODE_ENV: production

volumes:
  atom_data:
